name: base_rec
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - anaconda-anon-usage=0.7.6
  - annotated-types=0.7.0
  - antlr-python-runtime=4.9.3
  - aom=3.6.1
  - astroid=4.0.4
  - autopep8=2.0.4
  - backports.zstd=1.3.0
  - black=26.3.1
  - blas=1.0
  - bleach-with-css=6.3.0
  - brotli-bin=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.5.20
  - cached-property=1.5.2
  - cached_property=1.5.2
  - captum=0.8.0
  - colorama=0.4.6
  - conda=25.1.0
  - conda-content-trust=0.3.1
  - conda-libmamba-solver=25.4.0
  - cpp-expected=1.3.1
  - cpython=3.11.15
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=13.2.75
  - cuda-runtime=12.1.0
  - cuda-version=13.2
  - cycler=0.12.1
  - defusedxml=0.7.1
  - dill=0.4.1
  - distro=1.9.0
  - docstring-to-markdown=0.17
  - ffmpeg=4.4.2
  - flake8=7.1.2
  - fmt=12.0.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.17.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fqdn=1.5.1
  - freetype=2.14.3
  - giflib=5.2.2
  - gmp=6.3.0
  - gnutls=3.7.9
  - hpack=4.1.0
  - icu=75.1
  - intel-openmp=2023.0.0
  - ipython_pygments_lexers=1.1.1
  - isoduration=20.11.0
  - isort=8.0.1
  - jedi=0.19.2
  - jpeg=9e
  - jsonpatch=1.33
  - jsonpointer=3.1.1
  - jsonschema-with-format-nongpl=4.26.0
  - jupyterlab-lsp=5.3.0
  - jupyterlab_pygments=0.3.0
  - keyutils=1.6.3
  - krb5=1.22.2
  - lame=3.100
  - lark=1.3.1
  - lcms2=2.15
  - ld_impl_linux-64=2.45.1
  - lerc=4.1.0
  - libarchive=3.8.2
  - libblas=3.9.0
  - libboost=1.88.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcap=2.77
  - libcblas=3.9.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.17.1.22
  - libcurand=10.4.2.55
  - libcurl=8.19.0
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.17
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libexpat=2.7.5
  - libffi=3.4.6
  - libfreetype=2.14.3
  - libfreetype6=2.14.3
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libiconv=1.18
  - libidn2=2.3.8
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - liblightgbm=4.6.0
  - liblzma=5.8.3
  - liblzma-devel=5.8.3
  - libmamba=2.4.0
  - libmambapy=2.4.0
  - libnghttp2=1.68.1
  - libnl=3.11.0
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libpciaccess=0.18
  - libpng=1.6.58
  - libsodium=1.0.21
  - libsolv=0.7.36
  - libsqlite=3.53.0
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libsystemd0=260.1
  - libtasn1=4.21.0
  - libtiff=4.5.0
  - libudev1=260.1
  - libunistring=0.9.10
  - libuuid=2.42
  - libva=2.23.0
  - libvpx=1.13.1
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.2
  - lightgbm=4.6.0
  - llvm-openmp=15.0.7
  - lz4-c=1.9.4
  - mccabe=0.7.0
  - menuinst=2.4.2
  - mkl=2023.1.0
  - mpc=1.4.0
  - mpfr=4.2.2
  - munkres=1.1.4
  - mypy_extensions=1.1.0
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nettle=3.9.1
  - nlohmann_json-abi=3.12.0
  - notebook-shim=0.2.4
  - ocl-icd=2.3.3
  - omegaconf=2.3.0
  - opencl-headers=2025.06.13
  - openh264=2.3.1
  - openssl=3.6.2
  - overrides=7.7.0
  - p11-kit=0.24.1
  - pandas=2.3.3
  - pandocfilters=1.5.0
  - pathspec=1.0.4
  - pexpect=4.9.0
  - pillow=9.4.0
  - pip=26.0.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pybind11-abi=11
  - pycodestyle=2.12.1
  - pycosat=0.6.6
  - pydocstyle=6.3.0
  - pyflakes=3.2.0
  - pylint=4.0.5
  - pysocks=1.7.1
  - python=3.11.6
  - python-json-logger=2.0.7
  - python-lsp-jsonrpc=1.1.2
  - python-lsp-server=1.14.0
  - python-lsp-server-base=1.14.0
  - python_abi=3.11
  - pytokens=0.4.1
  - pytoolconfig=1.2.5
  - pytorch=2.5.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - qhull=2020.2
  - rdma-core=61.0
  - readline=8.3
  - reproc=14.2.7.post0
  - reproc-cpp=14.2.7.post0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rope=1.14.0
  - setuptools=82.0.1
  - simdjson=4.2.4
  - sniffio=1.3.1
  - snowballstemmer=3.0.1
  - svt-av1=1.4.1
  - tbb=2021.13.0
  - terminado=0.18.1
  - tk=8.6.13
  - tomlkit=0.14.0
  - torchaudio=2.5.1
  - torchtriton=3.1.0
  - torchvision=0.20.1
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - ujson=5.12.0
  - unicodedata2=17.0.1
  - uri-template=1.3.0
  - wayland=1.24.0
  - wayland-protocols=1.47
  - webencodings=0.5.1
  - whatthepatch=1.0.7
  - wheel=0.46.3
  - x264=1!164.3095
  - x265=3.5
  - xorg-libx11=1.8.13
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.7
  - xorg-libxfixes=6.0.2
  - xz=5.8.3
  - xz-gpl-tools=5.8.3
  - xz-tools=5.8.3
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - yapf=0.43.0
  - zeromq=4.3.5
  - zlib=1.3.2
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - accelerate==1.8.1
      - adjusttext==1.3.0
      - aiobotocore==2.23.0
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.9
      - aioitertools==0.12.0
      - aiosignal==1.3.1
      - anndata==0.10.9
      - annoy==1.17.3
      - anyio==4.6.0
      - archspec==0.2.3
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - array-api-compat==1.9
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==24.2.0
      - babel==2.14.0
      - beautifulsoup4==4.12.3
      - biopython==1.85
      - biothings-client==0.4.1
      - bleach==6.1.0
      - bokeh==3.7.3
      - boltons==24.0.0
      - boto3==1.38.27
      - botocore==1.38.27
      - brotli==1.1.0
      - causallib==0.10.0
      - cellxgene-census==1.17.0
      - cellxgene-ontology-guide==1.7.2
      - certifi==2026.1.4
      - cffi==1.17.1
      - charset-normalizer==3.3.2
      - chex==0.1.90
      - clearml==1.16.4
      - click==8.2.1
      - cloudpickle==3.1.1
      - colorcet==3.1.0
      - comm==0.2.2
      - conda-package-handling==2.3.0
      - conda-package-streaming==0.10.0
      - contourpy==1.3.0
      - coverage==7.10.1
      - cryptography==43.0.1
      - dask==2025.7.0
      - dask-expr==2.0.0
      - datashader==0.18.1
      - debugpy==1.8.6
      - decorator==5.1.1
      - deprecated==1.2.14
      - docopt==0.6.2
      - einops==0.8.0
      - entrypoints==0.4
      - et-xmlfile==2.0.0
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - fastjsonschema==2.20.0
      - fbpca==1.0
      - filelock==3.16.1
      - focal-loss-torch==0.1.2
      - fonttools==4.54.1
      - frozendict==2.4.5
      - frozenlist==1.4.1
      - fsspec==2024.9.0
      - ftpretty==0.4.0
      - furl==2.1.3
      - gensim==4.3.3
      - geoparse==2.0.4
      - geosketch==1.3
      - gmpy2==2.1.5
      - goatools==1.4.12
      - h11==0.14.0
      - h2==4.1.0
      - h5py==3.12.1
      - h5sparse==0.1.0
      - harmony-pytorch==0.1.8
      - hf-xet==1.1.5
      - hic-straw==1.3.1
      - holoviews==1.21.0
      - httpcore==1.0.6
      - httpx==0.27.2
      - huggingface-hub==0.36.0
      - hydra-core==1.3.2
      - hyperframe==6.0.1
      - idna==3.10
      - igraph==0.11.9
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - iniconfig==2.1.0
      - intervaltree==3.1.0
      - ipykernel==6.29.5
      - ipython==8.28.0
      - ipywidgets==8.1.5
      - jax==0.7.0
      - jaxlib==0.7.0
      - jinja2==3.1.4
      - jmespath==1.0.1
      - joblib==1.4.2
      - json5==0.9.25
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.4
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - legacy-api-wrap==1.4
      - leidenalg==0.10.2
      - lightning==2.4.0
      - lightning-utilities==0.11.7
      - linkify-it-py==2.0.3
      - litdata==0.2.50
      - llvmlite==0.43.0
      - locket==1.0.0
      - louvain==0.8.2
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - markupsafe==3.0.1
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - mistune==3.0.2
      - mizani==0.14.2
      - ml-dtypes==0.5.3
      - more-itertools==10.7.0
      - mpmath==1.3.0
      - multidict==6.1.0
      - multipledispatch==1.0.0
      - mygene==3.2.2
      - narwhals==2.0.1
      - natsort==8.4.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - networkx==3.3
      - notebook==7.3.2
      - numba==0.60.0
      - numexpr==2.11.0
      - numpy==1.26.4
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - orderedmultidict==1.0.1
      - packaging==24.1
      - pandera==0.24.0
      - panel==1.7.5
      - param==2.2.1
      - parso==0.8.4
      - partd==1.4.2
      - pathlib2==2.3.7.post1
      - patsy==0.5.6
      - peft==0.16.0
      - pickleshare==0.7.5
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.3.6
      - plotnine==0.15.0
      - plottable==0.1.5
      - pluggy==1.5.0
      - prometheus-client==0.21.0
      - prompt-toolkit==3.0.48
      - propcache==0.2.0
      - protobuf==5.28.2
      - psutil==6.0.0
      - pyarrow==20.0.0
      - pyarrow-hotfix==0.7
      - pybind11==2.13.6
      - pycparser==2.21
      - pyct==0.5.0
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pydot==3.0.2
      - pygments==2.18.0
      - pyjwt==2.8.0
      - pyliger==0.2.4
      - pynndescent==0.5.13
      - pyparsing==3.1.4
      - pysam==0.23.3
      - pytest==8.4.1
      - pytest-cov==6.2.1
      - python-dateutil==2.9.0
      - python-igraph==0.11.9
      - pytorch-lightning==2.4.0
      - pytz==2024.2
      - pyviz-comms==3.0.6
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - rdata==0.11.2
      - referencing==0.35.1
      - regex==2024.9.11
      - requests==2.32.3
      - rich==13.9.2
      - rnanorm==2.2.0
      - rpds-py==0.20.0
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.8
      - s3fs==2024.9.0
      - s3transfer==0.13.0
      - safetensors==0.4.5
      - scanorama==1.7.4
      - scanpy==1.10.3
      - scib==1.1.5
      - scib-metrics==0.5.6
      - scikit-learn==1.7.0
      - scikit-misc==0.5.1
      - scipy==1.13.1
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - session-info==1.0.0
      - shapely==2.1.1
      - six==1.16.0
      - smart-open==7.0.5
      - somacore==1.0.28
      - sortedcontainers==2.4.0
      - soupsieve==2.5
      - stack-data==0.6.2
      - statsmodels==0.14.5
      - stdlib-list==0.10.0
      - swatch==0.4.0
      - sympy==1.13.1
      - tblib==1.7.0
      - tensorboardx==2.6.2.2
      - texttable==1.7.0
      - threadpoolctl==3.5.0
      - tifffile==2025.6.11
      - tiledb==0.34.0
      - tiledb-cloud==0.13.0
      - tiledb-vector-search==0.13.0
      - tiledbsoma==1.17.0
      - tinycss2==1.3.0
      - tokenizers==0.22.1
      - tomli==2.0.2
      - toolz==1.0.0
      - torchdata==0.9.0
      - torchmetrics==1.1.0
      - tornado==6.4.1
      - tqdm==4.66.5
      - transformers==4.57.1
      - truststore==0.9.2
      - typeguard==4.4.4
      - types-python-dateutil==2.9.0.20241003
      - typing-inspect==0.9.0
      - tzdata==2024.2
      - uc-micro-py==1.0.3
      - umap-learn==0.5.6
      - urllib3==2.2.3
      - wcwidth==0.2.13
      - webcolors==24.8.0
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.13
      - wrapt==1.16.0
      - xarray==2025.7.0
      - xlsxwriter==3.2.5
      - xyzservices==2025.4.0
      - yarl==1.14.0
      - zipp==3.20.2
